server:
  port: 10010
spring:
  application:
    name: gateway-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
zuul:
  prefix: /api
  routes:
    item-service:
      path: /item/**
      serviceId: item-service
    upload-service:
      path: /upload/**
      serviceId: upload-service
    search-service:
      path: /search/**
      serviceId: search-service
    user-service:
      path: /user/**
      serviceId: user-service
ly:
  cors:
    allowedOrigins:
      - http://manage.leyou.com
      - http://www.leyou.com
    allowedCredentials: true
    allowedHeaders:
      - "*"
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 360000
    filterPath: "/**"