server:
  port: 10010
spring:
  application:
    name: gateway-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
zuul:
  prefix: /api
  routes:
    item-service:
      path: /item/**
      serviceId: item-service
    upload-service:
      path: /upload/**
      serviceId: upload-service
    search-service:
      path: /search/**
      serviceId: search-service
    user-service:
      path: /user/**
      serviceId: user-service
    auth-service:
      path: /auth/**
      serviceId: auth-service
    cart-service:
      path: /cart/**
      serviceId: cart-service
  sensitive-headers:
ly:
  cors:
    allowedOrigins:
      - http://manage.leyou.com
      - http://www.leyou.com
    allowedCredentials: true
    allowedHeaders:
      - "*"
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 360000
    filterPath: "/**"
  jwt:
    pubKeyPath: D:/ssh/id_rsa.pub # 公钥地址
    user:
      cookieName: LY_TOKEN # cookie名称
  filter:
    allowPaths:
      - /api/auth/login
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item