server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 10.0.75.2
    username: guest
    password: guest
    virtual-host: /
ly:
  sms:
    accessKeyID: LTAI4FtnrXZQ5VueT1Zat3Kf # 你自己的accessKeyId
    accessKeySecret: 3gK2KrHphQ5q6G5ST77yrufgRazLJ6 # 你自己的AccessKeySecret
    signName: 乐优商城验证码 # 签名名称
    verifyCodeTemplate: SMS_180950516 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id