server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  static:
    itemDir: D:\\Software\\nginx-1.12.2\\html\\item
    itemTemplate: item