server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 10.0.75.2
    username: guest
    password: guest
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  static:
    itemDir: D:\\Software\\nginx-1.12.2\\html\\item
    itemTemplate: item