server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
ly:
  oss:
    accessKeyId: LTAI4FtnrXZQ5VueT1Zat3Kf
    accessKeySecret: 3gK2KrHphQ5q6G5ST77yrufgRazLJ6
    host: http://image.leyou.com
    endpoint: oss-cn-beijing.aliyuncs.com
    dir: "" # 保存到bucket的某个子目录
    expireTime: 50 # 过期时间，单位是S
    maxFileSize: 5242880 #文件大小限制，这里是5M