spring:
  application:
    name: registry-service
server:
  port: 10086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    fetch-registry: false
    register-with-eureka: true