server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///leyou?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: 10.0.75.2
    username: guest
    password: guest
    virtual-host: /
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 80000ms
        multiplier: 2
    publisher-confirms: true
mybatis:
  mapper-locations: classpath:/mappers/*xml
  type-aliases-package: com.leyou.item.pojo
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
mapper:
  wrap-keyword: "`{0}`"
